package de.neozo.jblockchain.common.domain;


import de.neozo.jblockchain.common.Hashes;

import java.util.Arrays;

import static de.neozo.jblockchain.common.Bytes.toByteArray;

public class Transaction {
    /**
     * Unique identifier which can be generated by hashing text, senderHash, signature and timestamp
     */
    private final byte[] hash;

    /**
     * Payload of this transaction
     */
    private final byte[] payload;

    /**
     * The hash of the address which is responsible for this Transaction
     */
    private final byte[] sender;

    /**
     * Signature of text which can be verified with publicKey of sender address
     */
    private final byte[] signature;

    /**
     * Creation time of this Transaction
     */
    private final long timestamp;

    public Transaction(byte[] payload, byte[] senderHash, byte[] signature, long timestamp) {
        this.payload = payload;
        this.sender = senderHash;
        this.signature = signature;
        this.timestamp = timestamp;
        this.hash = calculateHash();
    }

    public byte[] getHash() {
        return hash;
    }

    public byte[] getPayload() {
        return payload;
    }

    public byte[] getSender() {
        return sender;
    }

    public byte[] getSignature() {
        return signature;
    }

    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Calculates the hash using relevant fields of this type
     *
     * @return SHA256-hash as raw bytes
     */
    public byte[] calculateHash() {
        return Hashes.digest(
                payload,
                sender,
                signature,
                toByteArray(timestamp)
        );
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Transaction that = (Transaction) o;

        return Arrays.equals(hash, that.hash);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(hash);
    }
}
